use crate::stage::{
    Stage,
    tokenize::{SourceFile, Span},
};
use bevy_app::prelude::*;
use bevy_ecs::{
    error::{BevyError, ErrorContext},
    prelude::*,
};
use bevy_log::error;
use bevy_state::state::{State, StateTransition};
use std::{
    io::IsTerminal,
    sync::atomic::{AtomicUsize, Ordering},
};

pub fn plugin(app: &mut App) {
    app.add_systems(StateTransition, check_stage_error)
        .set_error_handler(pretty_print);
}

static ERROR: AtomicUsize = AtomicUsize::new(0);
pub fn check_stage_error(stage: Res<State<Stage>>) {
    if ERROR.load(Ordering::SeqCst) > 0 {
        error!("Error encountered in {:?}", *stage);
        std::process::exit(1);
    }
}

#[inline]
#[track_caller]
fn pretty_print(error: BevyError, ctx: ErrorContext) {
    ERROR.fetch_add(1, Ordering::SeqCst);
    if let Some(err) = error.downcast_ref::<Error>() {
        pretty_print_error(
            err.span.location,
            err.span.start,
            err.span.end,
            &err,
            &ctx.name(),
        );
    } else if let Some(err) = error.downcast_ref::<crate::stage::parse::Error>() {
        pretty_print_error(
            err.span.location,
            err.span.start,
            err.span.end,
            &err,
            &err.location,
        );
    } else if let Some(err) = error.downcast_ref::<crate::stage::tokenize::Error>() {
        pretty_print_error(err.location, err.index, err.index + 1, &err, &ctx.name());
    } else {
        bevy_ecs::error::error(error, ctx);
    }
}

fn pretty_print_error(
    file: &SourceFile,
    start: usize,
    end: usize,
    err: &impl std::fmt::Display,
    _location: &impl std::fmt::Display,
) {
    let path = &file.path;
    let content = file.content;
    let stdout = std::io::stdout();
    let mut position = 0;
    for (i, line) in content.as_bytes().split(|b| *b == b'\n').enumerate() {
        let len = line.len() + 1;
        if len + position >= start {
            let offset = start - position + 7;
            if stdout.is_terminal() {
                println!("\x1b[91m\x1b[4m{path}:{}:{}: {err}\x1b[0m", i + 1, offset);
            } else {
                println!("{path}:{}:{}: {err}", i + 1, offset);
            }
            #[cfg(debug_assertions)]
            println!("Generated by {}", _location);
            println!("> {}", unsafe { str::from_utf8_unchecked(line) });
            for _ in 0..offset {
                print!(" ");
            }
            for _ in start..end.min(len + position) {
                print!("^");
            }
            println!();
            break;
        }
        position += len;
    }
}

#[derive(Debug)]
pub struct Error {
    pub span: Span,
    pub kind: ErrorKind,
}

#[derive(Debug)]
pub enum ErrorKind {
    Custom(&'static str),
    Msg(String),
    NoReturns,
}

impl std::error::Error for Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match &self.kind {
            ErrorKind::Custom(msg) => f.write_str(msg),
            ErrorKind::Msg(msg) => f.write_str(msg),
            ErrorKind::NoReturns => f.write_str("No return types specified"),
        }
    }
}

pub trait SpannedReport {
    fn spanned(&self, kind: ErrorKind) -> Error;
}

impl SpannedReport for Span {
    fn spanned(&self, kind: ErrorKind) -> Error {
        Error { span: *self, kind }
    }
}

impl<T> Report for T where T: SpannedReport {}
pub trait Report: SpannedReport {
    fn custom(&self, msg: &'static str) -> Error {
        self.spanned(ErrorKind::Custom(msg))
    }
    fn msg(&self, msg: String) -> Error {
        self.spanned(ErrorKind::Msg(msg))
    }
    fn kind(&self, kind: ErrorKind) -> Error {
        self.spanned(kind)
    }
}
